name: Deploying ArgoCD + SealedSecrets

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME_HML: togglemaster-eks-hml
  EKS_CLUSTER_NAME_PRD: togglemaster-eks

jobs:
  Deploy-CD-HML:
    if: ${{ inputs.environment == 'homologation' }} #Homologation environment
    name: Deploy CD HML
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest

      - name: Verify kubectl
        run: |
          echo "kubectl version: $(kubectl version --client)"

      - name: Get EKS cluster info
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME_HML }}
          echo "current context: $(kubectl config current-context)"
          echo "current nodes: $(kubectl get nodes)"

      - name: Creating namespaces
        run: |
          kubectl create namespace auth-service --dry-run=client -o yaml | kubectl apply -f -
          kubectl create namespace flag-service --dry-run=client -o yaml | kubectl apply -f -
          kubectl create namespace targeting-service --dry-run=client -o yaml | kubectl apply -f -
          kubectl create namespace evaluation-service --dry-run=client -o yaml | kubectl apply -f -
          kubectl create namespace analytics-service --dry-run=client -o yaml | kubectl apply -f -

      - name: apply ArgoCD
        run: |
          kubectl apply --server-side --force-conflicts -k CD/base/
          kubectl wait --for=condition=Established crd/applications.argoproj.io --timeout=60s
          kubectl wait --for=condition=Established crd/appprojects.argoproj.io --timeout=60s
          kubectl wait --for=condition=Established crd/applicationsets.argoproj.io --timeout=60s
          kubectl apply --server-side --force-conflicts -k CD/apps/

      - name: Verifying ArgoCD
        run: |
          echo "ArgoCD version: $(kubectl get deployment argocd-server -n argocd -o jsonpath='{.spec.template.spec.containers[0].image}')"

      - name: Create Metrics server
        run: |
          kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/high-availability-1.21+.yaml

      - name: Create Ingress NGINX
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.9.6/deploy/static/provider/cloud/deploy.yaml

      - name: Create namespace for Sealed Secrets
        run: |
          kubectl create namespace sealed-secrets --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploying SealedSecret
        run: |
          helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets
          helm repo update
          kubectl create namespace sealed-secrets --dry-run=client -o yaml | kubectl apply -f -
          helm upgrade --install sealed-secrets sealed-secrets/sealed-secrets \
            -n sealed-secrets \
            --create-namespace \
            --wait

      - name: Verifying SealedSecret
        run: |
          kubectl get deployment sealed-secrets -n sealed-secrets
          kubectl get pods -n sealed-secrets
          kubectl get secret -n sealed-secrets

      - name: Deploying SQL Databases
        run: |
          echo "SQL Databases will be deployed here"
          cd jobs/init_sql/
          kubectl apply -f configmap.yaml
          kubectl apply -f create-databases.yaml
          kubectl apply -f test-job.yaml

  Deploy-CD-PRD:
    if: ${{ inputs.environment == 'production' }} #Production environment
    name: Deploy CD PRD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest

      - name: Verify kubectl
        run: |
          echo "kubectl version: $(kubectl version --client)"

      - name: Get EKS cluster info
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME_PRD }}
          echo "current context: $(kubectl config current-context)"
          echo "current nodes: $(kubectl get nodes)"

      - name: apply ArgoCD
        run: |
          kubectl apply --server-side --force-conflicts -k CD/base/
          kubectl wait --for=condition=Established crd/applications.argoproj.io --timeout=60s
          kubectl wait --for=condition=Established crd/appprojects.argoproj.io --timeout=60s
          kubectl wait --for=condition=Established crd/applicationsets.argoproj.io --timeout=60s
          kubectl apply --server-side --force-conflicts -k CD/apps/

      - name: Create Metrics server
        run: |
          kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/high-availability-1.21+.yaml

      - name: Create Ingress NGINX
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.9.6/deploy/static/provider/cloud/deploy.yaml

      - name: Verifying ArgoCD
        run: |
          echo "ArgoCD version: $(kubectl get deployment argocd-server -n argocd -o jsonpath='{.spec.template.spec.containers[0].image}')"

      - name: Create namespace for Sealed Secrets
        run: |
          kubectl create namespace sealed-secrets --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploying SealedSecret
        run: |
          helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets
          helm repo update
          kubectl create namespace sealed-secrets --dry-run=client -o yaml | kubectl apply -f -
          helm upgrade --install sealed-secrets sealed-secrets/sealed-secrets \
            -n sealed-secrets \
            --create-namespace \
            --wait

      - name: Verifying SealedSecret
        run: |
          kubectl get deployment sealed-secrets -n sealed-secrets
          kubectl get pods -n sealed-secrets
          kubectl get secret -n sealed-secrets

      - name: Deploying SQL Databases
        run: |
          echo "SQL Databases will be deployed here"
          cd jobs/init_sql/
          kubectl apply -f configmap.yaml
          kubectl apply -f create-databases.yaml
          kubectl apply -f test-job.yaml